
title: COMPUNET-ONLINE
email: OLIVER@example.com
description: >- # this means to ignore newlines until "baseurl:"
  somos una tienda 100% online de equipos de computo, contamos con
  todas la gamas de equipos
baseurl: "/myNewSite" # the subpath of your site, e.g. /blog
url: "https://ovigilio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: oliver
github_username:  ovigilio

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
